version: 0.2
env:
  git-credential-helper: yes
phases:
  install:
    commands:
      - yum -y update
      - yum -y install jq
      - yum -y install java-1.8.0-openjdk
  pre_build:
    commands:
      - mkdir /downloads/sonarqube -p
      - cd /downloads/sonarqube
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.2.0.1873-linux.zip
      - unzip sonar-scanner-cli-4.2.0.1873-linux.zip
      - mv sonar-scanner-4.2.0.1873-linux /opt/sonar-scanner
      - echo -e "sonar.host.url=http://127.0.0.1:9000/ \n  sonar.sourceEncoding=UTF-8 \n sonar.qualitygate.wait=true " >> /opt/sonar-scanner/conf/sonar-scanner.properties
      - echo -e "#/bin/bash \n export PATH='$PATH:/opt/sonar-scanner/bin'" >> /etc/profile.d/sonar-scanner.sh
      - source /etc/profile.d/sonar-scanner.sh
      - sonar-scanner -v
  build:
    commands:
      - docker run --rm -p 9000:9000 -d --name sonarserver public.ecr.aws/i3o0y1a9/sonarqube
      - IP_ADDRESS=`docker inspect sonarserver | jq -r ".[] .NetworkSettings.Networks.bridge.IPAddress"`
      - sleep 100
      - git clone $CLONE_URL
      - cd $REPO_NAME
      - sonar-scanner -Dsonar.projectKey=Test_Project -Dsonar.sources=. -Dsonar.host.url=http://127.0.0.1:9000  -Dsonar.login="admin" -Dsonar.password="admin"
      - curl -u admin:admin -o $NAME.json http://3.238.56.205:9000/api/issues/search
  post_build:
    commands:
      - echo "Uploading JSON file as artifact"
      - aws s3 cp $NAME.json $S3_URL/$NAME.json
      - |
        curl \
        -X POST \
        "$UPDATE_POJRCT_URL?s3_bucket_name=$S3_BUCKET_NAME&repo_name=$NAME&username=$USERNAME"
